<?php

//si esta activo internacionalizacion url
$config['urli18n'] = true;

/** --- AUTOGENERATED --- **/

$alias['bienvenido'] = array (
	'lang' => 'es',
	'name' => 'welcome',
	'method' => array (
		'indice' => 'index',
		'prueba' => 'demo',
	)
);

$alias['welcome'] = array (
	'lang' => 'en',
	'name' => 'welcome',
	'method' => array (
		'index' => 'index',
		'demo' => 'demo',
	)
);

